"""
braid_simulator/word.py — Braid Algebra Engine

Implements the algebraic foundation of Braided Computational Topology:

  * Generator / BraidWord / NormalForm data types
  * sigma(i, n) and sigma_inv(i, n) constructors
  * reduce_to_normal_form(word) — canonical form via BFS over equivalence class
  * is_equivalent(W, W') — equality in B_n
  * check_topological_equivalence(W, W') — raises TopologicalMismatchFault on mismatch

The canonical form is computed by exhaustive BFS over the equivalence class
generated by:
  1. Free cancellation          σ_i σ_i^{-1} = ε,  σ_i^{-1} σ_i = ε
  2. Far commutativity          σ_i σ_j = σ_j σ_i          for |i − j| ≥ 2
  3. Braid relation             σ_i σ_{i+1} σ_i = σ_{i+1} σ_i σ_{i+1}
     (and its all-negative form for σ^{-1} generators)

The lex-minimal word in the equivalence class is taken as the canonical form.
BFS terminates because braid/commutativity rules preserve word length and there
are finitely many words of each length; free cancellation strictly shortens words.

LIMITATION: The mixed-sign braid relation (e.g. σ_i σ_{i+1}^{-1} σ_i^{-1} = ...)
is NOT applied directly — it is reachable only via free cancellation + the positive
or negative braid relations. For positive braid words (no inverses), the normal
form is provably complete and correct.
"""
from __future__ import annotations

from collections import deque
from typing import NamedTuple

# Safety bound to prevent runaway BFS on unexpectedly large inputs.
_MAX_STATES: int = 50_000


# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------

class Generator(NamedTuple):
    """
    A single Artin braid generator.

    index   — 1-based position: σ_1, σ_2, ..., σ_{n-1}
    inverse — True for σ_index^{-1}, False for σ_index
    """

    index: int
    inverse: bool = False

    def __neg__(self) -> "Generator":
        return Generator(self.index, not self.inverse)

    def cancels(self, other: "Generator") -> bool:
        """True iff self and other are inverses: same index, opposite sign."""
        return self.index == other.index and self.inverse != other.inverse

    def __repr__(self) -> str:
        sup = "⁻¹" if self.inverse else ""
        return f"σ_{self.index}{sup}"


class NormalForm(NamedTuple):
    """
    The canonical (lex-minimal) representative of a braid word's equivalence class.

    n         — number of strands (the braid group B_n)
    canonical — lex-minimal word as a tuple of Generator objects
    """

    n: int
    canonical: tuple[Generator, ...]

    def __repr__(self) -> str:
        if not self.canonical:
            return f"NF(B{self.n}, ε)"
        word = " · ".join(repr(g) for g in self.canonical)
        return f"NF(B{self.n}, {word})"


class BraidWord:
    """
    A word in the braid group B_n.

    Constructed from Generator tuples.  Two BraidWord objects represent the same
    braid iff reduce_to_normal_form gives the same NormalForm for both.

    Use sigma() / sigma_inv() or the * operator to build words:

        w = sigma(1, 3) * sigma(2, 3) * sigma(1, 3)   # σ_1 σ_2 σ_1 in B_3
    """

    def __init__(self, n: int, generators: tuple[Generator, ...] | list[Generator]) -> None:
        if n < 2:
            raise ValueError(f"B_n requires n ≥ 2, got n={n}")
        self.n = n
        self.generators: tuple[Generator, ...] = tuple(generators)
        for g in self.generators:
            if not 1 <= g.index <= n - 1:
                raise ValueError(
                    f"Generator σ_{g.index} is not valid for B_{n}: "
                    f"index must be in [1, {n - 1}]"
                )

    # ------------------------------------------------------------------
    # Arithmetic
    # ------------------------------------------------------------------

    def __mul__(self, other: "BraidWord") -> "BraidWord":
        if self.n != other.n:
            raise ValueError(
                f"Cannot concatenate words from different groups: B_{self.n} and B_{other.n}"
            )
        return BraidWord(self.n, self.generators + other.generators)

    # ------------------------------------------------------------------
    # Equality and hashing (syntactic — use is_equivalent for semantic)
    # ------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, BraidWord):
            return NotImplemented
        return self.n == other.n and self.generators == other.generators

    def __hash__(self) -> int:
        return hash((self.n, self.generators))

    def __repr__(self) -> str:
        if not self.generators:
            return f"BraidWord(B{self.n}, ε)"
        word = " · ".join(repr(g) for g in self.generators)
        return f"BraidWord(B{self.n}, {word})"


# ---------------------------------------------------------------------------
# Constructors
# ---------------------------------------------------------------------------

def sigma(index: int, n: int) -> BraidWord:
    """Return the single-generator braid word σ_index in B_n."""
    if not 1 <= index <= n - 1:
        raise ValueError(
            f"σ_{index} is not a generator of B_{n}: index must be in [1, {n - 1}]"
        )
    return BraidWord(n=n, generators=(Generator(index, False),))


def sigma_inv(index: int, n: int) -> BraidWord:
    """Return the single-generator braid word σ_index^{-1} in B_n."""
    if not 1 <= index <= n - 1:
        raise ValueError(
            f"σ_{index}^{{-1}} is not a generator of B_{n}: index must be in [1, {n - 1}]"
        )
    return BraidWord(n=n, generators=(Generator(index, True),))


# ---------------------------------------------------------------------------
# Rewriting rules
# ---------------------------------------------------------------------------

def _free_reduce(gens: tuple[Generator, ...]) -> tuple[Generator, ...]:
    """
    Apply free group cancellation exhaustively.

    Removes adjacent pairs σ_i σ_i^{-1} and σ_i^{-1} σ_i until no such pair
    remains.  The result is the unique free-reduced representative of the given
    word in the free group on {σ_1^{±1}, ..., σ_{n-1}^{±1}}.
    """
    stack: list[Generator] = []
    for g in gens:
        if stack and stack[-1].cancels(g):
            stack.pop()
        else:
            stack.append(g)
    return tuple(stack)


def _one_step_neighbors(gens: tuple[Generator, ...]) -> list[tuple[Generator, ...]]:
    """
    Return every word obtainable from gens by exactly one relation application.

    Relations applied (both directions automatically via BFS):
      1. Far commutativity: swap σ_i^{±1} σ_j^{±1} when |i − j| ≥ 2
      2. Braid relation:    (a, b, a) → (b, a, b)
             where a.index and b.index are adjacent (|a.index − b.index| == 1)
             and both generators have the same sign (both positive or both negative)
    """
    results: list[tuple[Generator, ...]] = []
    n = len(gens)

    for pos in range(n):
        # ── Far commutativity (length-2 swap) ──────────────────────────────
        if pos + 1 < n:
            a, b = gens[pos], gens[pos + 1]
            if abs(a.index - b.index) >= 2:
                results.append(gens[:pos] + (b, a) + gens[pos + 2:])

        # ── Braid relation (length-3 swap) ─────────────────────────────────
        if pos + 2 < n:
            a, b, c = gens[pos], gens[pos + 1], gens[pos + 2]
            # Pattern: (a, b, a) where a == c and generators are adjacent same-sign
            if (
                a == c
                and abs(a.index - b.index) == 1
                and a.inverse == b.inverse   # all same sign (both positive or both negative)
            ):
                # Rewrite: (a, b, a) → (b, a, b)
                results.append(gens[:pos] + (b, a, b) + gens[pos + 3:])

    return results


# ---------------------------------------------------------------------------
# Normal form computation
# ---------------------------------------------------------------------------

def reduce_to_normal_form(word: BraidWord) -> NormalForm:
    """
    Compute the canonical normal form of a braid word.

    Algorithm: BFS over the equivalence class reachable via free cancellation,
    far commutativity, and the braid relation.  The lex-minimal word (shortest
    first, then lexicographic by (index, int(inverse))) is the canonical form.

    Two braid words W and W' represent the same element of B_n if and only if
    reduce_to_normal_form(W) == reduce_to_normal_form(W').

    Correctness guarantee (positive words): For braid words with no inverse
    generators, the BFS is provably complete — all derivable equivalences via
    far commutativity and the braid relation are explored.

    Raises RuntimeError if the equivalence class exceeds _MAX_STATES elements
    (safety guard against pathological inputs; not triggered by normal use).
    """
    start = _free_reduce(word.generators)

    visited: set[tuple[Generator, ...]] = set()
    queue: deque[tuple[Generator, ...]] = deque([start])
    visited.add(start)

    while queue:
        current = queue.popleft()

        if len(visited) > _MAX_STATES:
            raise RuntimeError(
                f"reduce_to_normal_form: equivalence class exceeded {_MAX_STATES} states. "
                "Use shorter braid words (length ≤ ~12 for n ≤ 5 is safe)."
            )

        for neighbor in _one_step_neighbors(current):
            reduced = _free_reduce(neighbor)
            if reduced not in visited:
                visited.add(reduced)
                queue.append(reduced)

    # Lex-minimal representative: shortest first, then (index, int(inverse)) tuples.
    def _word_key(w: tuple[Generator, ...]) -> tuple:
        return (len(w),) + tuple((g.index, int(g.inverse)) for g in w)

    canonical = min(visited, key=_word_key)
    return NormalForm(n=word.n, canonical=canonical)


# ---------------------------------------------------------------------------
# Equivalence and mismatch detection
# ---------------------------------------------------------------------------

def is_equivalent(W: BraidWord, W_prime: BraidWord) -> bool:
    """
    Return True iff W and W' represent the same element of B_n.

    Equivalent to: reduce_to_normal_form(W) == reduce_to_normal_form(W')
    """
    if W.n != W_prime.n:
        return False
    return reduce_to_normal_form(W) == reduce_to_normal_form(W_prime)


def check_topological_equivalence(W: BraidWord, W_prime: BraidWord) -> None:
    """
    Verify that W and W' represent the same braid in B_n.

    Raises TopologicalMismatchFault if their normal forms differ.

    This is the verification engine entry point for proof obligation PO-1.
    A reordering that satisfies the braid relation (e.g. σ_1 σ_2 σ_1 → σ_2 σ_1 σ_2)
    will NOT trigger this fault.  An illegal adjacent transposition (e.g. swapping
    σ_1 σ_2 to σ_2 σ_1 without the three-crossing braid relation) WILL trigger it.
    """
    # Import here to avoid circular imports; TopologicalMismatchFault lives in execution.py.
    from .execution import TopologicalMismatchFault  # noqa: PLC0415

    if W.n != W_prime.n:
        raise TopologicalMismatchFault(
            f"Topological mismatch: words are from different groups "
            f"B_{W.n} and B_{W_prime.n}"
        )

    nf_W = reduce_to_normal_form(W)
    nf_W_prime = reduce_to_normal_form(W_prime)

    if nf_W != nf_W_prime:
        raise TopologicalMismatchFault(
            f"Topological mismatch detected.\n"
            f"  W        = {W!r}\n"
            f"  W'       = {W_prime!r}\n"
            f"  NF(W)    = {nf_W!r}\n"
            f"  NF(W')   = {nf_W_prime!r}\n"
            "The reordering is not an instance of far-commutativity or the braid "
            "relation — it is a topological fault."
        )
